//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.549, BuildCommit: 3da8ece356e0f31d6b3a8e7f419e446ace69898f)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15, SDK: 15, Tool: ld (1115.7.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18, SDK: 18, Tool: ld (1115.7.3)
//    - LC_SOURCE_VERSION: 1149.6.2.0.0
//
#ifndef CABackdropLayer_h
#define CABackdropLayer_h

#include <QuartzCore/CALayer.h>

@import Foundation;

@protocol CABackdropLayerDelegate, CALayerDelegate;

@interface CABackdropLayer : CALayer

@property BOOL enabled;
@property (copy) NSString *groupName;
@property BOOL usesGlobalGroupNamespace;
@property (copy) NSString *groupNamespace;
@property double scale;
@property CGRect backdropRect;
@property double marginWidth;
@property BOOL disablesOccludedBackdropBlurs;
@property BOOL captureOnly;
@property BOOL allowsInPlaceFiltering;
@property BOOL reducesCaptureBitDepth;
@property BOOL ignoresScreenClip;
@property double bleedAmount;
@property BOOL windowServerAware;
@property BOOL inverseMeshed;
@property BOOL allowsSubstituteColor;
@property struct CGColor * substituteColor;
@property BOOL ignoresOffscreenGroups;
@property double zoom;
@property (weak) id <CABackdropLayerDelegate, CALayerDelegate> delegate;

/* class methods */
+ (void)initialize;
+ (id)defaultValueForKey:(id)key;
+ (id)CA_attributes;
+ (BOOL)CA_automaticallyNotifiesObservers:(Class)observers;
+ (BOOL)_hasRenderLayerSubclass;

/* instance methods */
- (void)didChangeValueForKey:(id)key;
- (BOOL)isEnabled;
- (void)layerDidBecomeVisible:(BOOL)visible;
- (BOOL)isInverseMeshed;
- (void *)_copyRenderLayer:(void *)layer layerFlags:(unsigned int)flags commitFlags:(unsigned int *)flags;
- (void)_renderBackgroundInContext:(struct CGContext *)context;
- (_Bool)_renderLayerDefinesProperty:(unsigned int)property;
- (unsigned int)_renderLayerPropertyAnimationFlags:(unsigned int)flags;

@end

#endif /* CABackdropLayer_h */
