name: Style fix and check
on:
  pull_request:
    branches: ["master", "develop"]
    paths:
      - '**.swift'

jobs:
  swift-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint (fix)
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --fix
      - name: Lint (check)
        id: swiftlint-output
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --config .swiftlint.yml
      - name: Saving changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: swiftlint --fix --format auto run
