name: Style check
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  swift-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --fix --format
        env:
          DIFF_BASE: ${{ github.base_ref }}
      - name: Saving changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: swiftlint --fix --format auto run