name: Build and Analyze
on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

concurrency:
# check if this works
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-coverage-result:
    runs-on: ubuntu-latest
    # needs: analyze
    steps:
      - uses: actions/github-script@v6
        id: get-run
        with:
          script: |
            const workflowruns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'xcode-build.yml',
              per_page: 1,
            });
            const last_run_id = workflowruns.data.workflow_runs[0].id
            const artifacts = await github.rest.checks.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: last_run_id,
            });
            return artifacts.data
      - name: Get result
        run: echo "${{ steps.get-run.outputs.result }}"