name: Build and Analyze
on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-and-coverage:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set xcode version
        run: |
          sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Test
        env:
          FASTLANE_EXPLICIT_OPEN_SIMULATOR: "2"
        run: |
          xcodebuild -project SlimHUD.xcodeproj -scheme SlimHUD -destination platform=macOS -sdk macosx13.1 CODE_SIGNING_ALLOWED=NO -resultBundlePath TestResults clean test
      - uses: kishikawakatsumi/xcresulttool@v1.7.0
        if: success() || failure()
        with:
          path: TestResults.xcresult
          show-code-coverage: true
          upload-bundles: always
