name: Build and Analyze
on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  # analyze:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Test
  #       run: |
  #         xcodebuild -workspace SlimHUD.xcworkspace -scheme SlimHUD -destination platform=macOS -resultBundlePath TestResults test
  #     - name: Create coverage
  #       id: code-coverage
  #       uses: kishikawakatsumi/xcresulttool@v1
  #       with:
  #         path: TestResults.xcresult
  #         show-code-coverage: true
  get-coverage-result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const result = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            return result
      - name: Get result
        run: echo "${{ steps.set-result.outputs.result }}"
  update-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: NejcZdovc/comment-pr@v2
        with:
          message: "Hello world 2"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}