name: Xcode - Build and Analyze
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - uses: actions/checkout@v3
      - uses: slashmo/install-swift@v0.2.1
        with:
          version: 5.3.2
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: SlimHUD.xcworkspace
          scheme: SlimHUD
          destination: platform=macOS
          action: build

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - uses: actions/checkout@v3
      - uses: slashmo/install-swift@v0.2.1
        with:
          version: 5.3.2
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: SlimHUD.xcworkspace
          scheme: SlimHUD
          destination: platform=macOS
          action: test

  swiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
      - name: GitHub Action for SwiftLint (Different working directory)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: Source

