name: Xcode - Build and Analyze
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: SlimHUD.xcworkspace
          scheme: SlimHUD
          destination: platform=macOS
          action: build
          
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - macOS
    steps:
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: SlimHUD.xcworkspace
          scheme: SlimHUD
          destination: platform=macOS
          action: test

