name: Build and Analyze
on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild -workspace SlimHUD.xcworkspace -scheme SlimHUD -destination platform=macOS -resultBundlePath TestResults test
      - name: Create coverage
        id: code-coverage
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
          title: test-results
          show-code-coverage: true
      - uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: test-results