name: Build and Analyze
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "unitests${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  test-results-check-name: Unit Test results

jobs:
  unit-tests-run:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Switch Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test
        continue-on-error: true
        run: |
          xcodebuild clean test \
          -project SlimHUD.xcodeproj \
          -scheme SlimHUD-GitHub-Action \
          -destination platform=macOS \
          -resultBundlePath TestResults \
          -test-iterations 3 -retry-tests-on-failure \
          CODE_SIGNING_ALLOWED=NO
      - name: Post test results
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: "TestResults.xcresult"
          title: ${{ env.test-results-check-name }}
          upload-bundles: never
          show-code-coverage: true
      - name: Generate coverage report
        run: |
          bash ./Configuration/xccov-to-sonarqube-generic.sh TestResults.xcresult/ > sonarqube-generic-coverage.xml
          sed -i '' "s/projectVersion=1.0/projectVersion=$(xcrun agvtool what-version -terse) /g" sonar-project.properties
      - name: Save coverage report
        uses: actions/upload-artifact@master
        with:
          name: sonarqube-generic-coverage
          path: sonarqube-generic-coverage.xml
          

  sonarcloud:
    name: SonarCloud scan
    runs-on: ubuntu-latest
    needs: unit-tests-run
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/download-artifact@master # download all previously generated artifacts
        with:
          name: sonarqube-generic-coverage
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        run: |
          sonar-scanner