name: Build and Analyze
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: slashmo/install-swift@v0.2.1
        with:
          version: 5.3.2
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: SlimHUD.xcworkspace
          scheme: SlimHUD
          destination: platform=macOS
          action: test

  coverage:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild -workspace SlimHUD.xcworkspace -scheme SlimHUD -destination platform=macOS -resultBundlePath TestResults test
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
          show-code-coverage: true
