name: Build and Analyze
on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  concurrency: 
    group: ${{ github.head_ref }}
    cancel-in-progress: true
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild -workspace SlimHUD.xcworkspace -scheme SlimHUD -destination platform=macOS -resultBundlePath TestResults test
      - name: Create coverage
        id: code-coverage
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
          show-code-coverage: true
  get-coverage-result:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/github-script@v6
        id: get-workflow
        with:
          script: |
            const workflowruns = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            const last_run_id = workflowruns.data.workflow_runs[0].id
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: last_run_id,
            });
            return artifacts.data
      - name: Get result
        run: echo "${{ steps.get-workflow.outputs.result }}"
  # update-comment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: NejcZdovc/comment-pr@v2
  #       with:
  #         message: "Hello world 3"
  #       env:
  #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}