name: Build and Analyze
on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild -workspace SlimHUD.xcworkspace -scheme SlimHUD -destination platform=macOS -resultBundlePath TestResults test
      - name: Create coverage
        id: code-coverage
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
          show-code-coverage: true
  write-comment:
#    if: ${{ github.event.issue.pull_request }}
# github.event.number # MR number
# github.event.after # commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.createReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: github.event.number,
              body: 'Test',
              commit_id: github.event.after,
              path: README.md,
              line: 1
            });
  get-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: github.event.number,
              review_id,
            });